name: CI

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
    build_nalgebra:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --features=nalgebra-support --verbose
      - name: Run tests
        run: cargo test --features=nalgebra-support --verbose
